// Privated Credentials
const APP_PORT = process.env.APP_PORT || 8080;
const CLIENT_ORIGIN = process.env.CLIENT_ORIGIN;
const JWT_SECRET_KEY = process.env.JWT_SECRET_KEY;
const DB_URI = process.env.DB_URI!;
const DIRECT_DB_URL = process.env.DIRECT_DB_URL!;
const ENVIRONMENT = process.env.ENVIRONMENT;

const WHITELISTED_ORIGINS = [CLIENT_ORIGIN];

const ENV_VARS = {
  PORT: APP_PORT,
  JWT_SECRET: JWT_SECRET_KEY!,
  CLIENT_ORIGIN: CLIENT_ORIGIN,
  DB_URI: DB_URI,
  DIRECT_DB_URI: DIRECT_DB_URL,
  ENV: ENVIRONMENT,
};

export { ENV_VARS, WHITELISTED_ORIGINS };

const ZOD_REQUIRED_ERR = "{field} is required";

export { ZOD_REQUIRED_ERR };

// SERVER RESPONSE
const BAD_REQUEST_STATUS_CODE = 400;
const UNAUTHORIZED_REQUEST_STATUS_CODE = 401;
const CONFLICT_REQUEST_STATUS_CODE = 409;

// JWT
const CURRENT_DATE_IN_JWT_FORM = Math.floor(Date.now() / 1000);

const RESPONSE_MESSAGES = {
  AUTH: {
    CODES: {
      BAD_REQUEST: BAD_REQUEST_STATUS_CODE,
      UNAUTHORIZED: UNAUTHORIZED_REQUEST_STATUS_CODE,
      CONFLICT: CONFLICT_REQUEST_STATUS_CODE,
    },
  },
};

const JWT_CONSTANTS = {
  CURRENT_DATE: CURRENT_DATE_IN_JWT_FORM,
};

export { RESPONSE_MESSAGES, JWT_CONSTANTS };
