// Privated Credentials
const APP_PORT = process.env.APP_PORT || 8080;
const CLIENT_ORIGIN = process.env.CLIENT_ORIGIN;
const SERVER_ORIGIN = process.env.SERVER_ORIGIN;
const JWT_SECRET_KEY = process.env.JWT_SECRET_KEY;
const DB_URI = process.env.DB_URI!;
const DIRECT_DB_URL = process.env.DIRECT_DB_URL!;
const ENVIRONMENT = process.env.ENVIRONMENT;
const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID;
const GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET;
const GOOGLE_OAUTH_URL = process.env.GOOGLE_OAUTH_URL;
const GOOGLE_ACCESS_TOKEN_URL = process.env.GOOGLE_ACCESS_TOKEN_URL;
const GOOGLE_TOKEN_INFO_URL = process.env.GOOGLE_TOKEN_INFO_URL;

const WHITELISTED_ORIGINS = [CLIENT_ORIGIN];

const ENV_VARS = {
  PORT: APP_PORT,
  JWT_SECRET: JWT_SECRET_KEY!,
  CLIENT_ORIGIN: CLIENT_ORIGIN,
  SERVER_ORIGIN: SERVER_ORIGIN,
  DB_URI: DB_URI,
  DIRECT_DB_URI: DIRECT_DB_URL,
  ENV: ENVIRONMENT,
  GOOGLE: {
    CLIENT_ID: GOOGLE_CLIENT_ID,
    CLIENT_SECRET: GOOGLE_CLIENT_SECRET,
    OAUTH_URL: GOOGLE_OAUTH_URL,
    ACCESS_TOKEN_URL: GOOGLE_ACCESS_TOKEN_URL,
    TOKEN_INFO_URL: GOOGLE_TOKEN_INFO_URL,
  },
};

export { ENV_VARS, WHITELISTED_ORIGINS };

const ZOD_REQUIRED_ERR = "{field} is required";

export { ZOD_REQUIRED_ERR };

// SERVER RESPONSE
const BAD_REQUEST_STATUS_CODE = 400;
const UNAUTHORIZED_REQUEST_STATUS_CODE = 401;
const CONFLICT_REQUEST_STATUS_CODE = 409;

// JWT
const CURRENT_DATE_IN_JWT_FORM = Math.floor(Date.now() / 1000);

const RESPONSE_MESSAGES = {
  AUTH: {
    CODES: {
      BAD_REQUEST: BAD_REQUEST_STATUS_CODE,
      UNAUTHORIZED: UNAUTHORIZED_REQUEST_STATUS_CODE,
      CONFLICT: CONFLICT_REQUEST_STATUS_CODE,
    },
  },
};

const JWT_CONSTANTS = {
  CURRENT_DATE: CURRENT_DATE_IN_JWT_FORM,
};

export { RESPONSE_MESSAGES, JWT_CONSTANTS };
